@startuml Klassediagram

skin rose

title Stigespill - Klasse Diagram

class Stigespill{
	+Terning : Terning
	+Brett : Brett
	+Spillere : List<Spiller>
}
class Brett{
	+Ruter : List<Rute>
	+Stiger : List<Stige>
}
class Rute{
	+Posisjon : Integer
	+Stige : Stige
}
class Stige{
	+StartPos : Rute
	+SluttPos : Rute
}
class Spiller{
	+Navn : String
	+Brikke : Brikke
}
class Brikke{
	+Farge : String
	+Posisjon : Rute
}
class Terning{
	+Verdi : Integer
}

Brett "1" -down- "100 " Rute: Inneholder >
Brett "1   " -right- " 16" Stige: Inneholder >
Stige "0..1    " -down- "2" Rute : Har >
Stigespill "1  " -down- "2..4" Spiller: Spiller
Stigespill "1" -down- "1  " Brett
Stigespill "1   " -right- "   1" Terning: Spiller med
Spiller "1" -down- "1" Brikke: Eier >
Brikke "0..4" -right- "   1" Rute: Er på >

@enduml