@startuml Sekvensdiagram

skin rose

title "Stigespill - Sekvens Diagram"

participant ":Stigespill" as sp
participant ":Brett" as bt
participant ":Spiller" as s
participant ":Terning" as t
participant ":Brikke" as br
participant ":Rute" as r
participant ":Stige" as st
participant ":Slange" as sl

-> sp: Spill()
loop til vinn
	loop alle spillere
		sp -> s: spillTrekk()
		s -> t: steg = trill()
		s -> br: flytt(steg)
		br -> r: flytt(steg)
		br -> r: obstruksjon = harObstruksjon(rute)
		!includesub obstruksjon.plantuml!obs

		s -> br: rute = getRute()
		s -> s: spiller = getNavn()
		<-- s: steg, spiller, rute
	end
end


@enduml