@startuml Sekvensdiagram

skin rose

title "Stigespill - Sekvens Diagram"

participant ":Stigespill" as sp
participant ":Brett" as bt
participant ":Spiller" as s
participant ":Terning" as t
participant ":Brikke" as br
participant ":Rute" as r
participant ":Stige" as st
participant ":Slange" as sl

-> sp: Spill()
loop til vinn
	loop alle spillere
		sp -> s: spillTrekk()
		s -> t: trill()
		s -> t: steg = getVerdi()
		s -> br: flytt(steg)
		br -> r: flytt(steg)
		br -> r: obstruksjon = harObstruksjon(rute)
		alt obstruksjon == null
			br -> br
			note right
				Beholder denne ruten
			end note
		else obstruksjon == stige
			br -> st: rute = hentSluttRute()
			br -> r: flyttTilRute(rute)
		else obstruksjon == slange
			br -> sl: rute = hentSluttRute()
			br -> r: flyttTilRute(rute)
		end

		s -> br: rute = getRute()
		s -> s: spiller = getNavn()
		<-- s: steg, spiller, rute
	end
end


@enduml